import './employer.spec'
import './chart of accounts.spec'
import './absencereasons.spec'
import './department.spec'
import './qualification.spec'
import './skills.spec'
import './payplan.spec'
import './location.spec'
import './contact.spec'
import './employer.cleanup.spec'
import './termdates.spec'